import type { Metadata } from "next";
import { Lexend_Giga } from "next/font/google";
import "./globals.css";
import Header from "@/utils/Header";
import Aurora from "../utils/Aurora";

const lexendGiga = Lexend_Giga({
  variable: "--lexend-giga",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexendGiga.variable} antialiased py-[70px] relative`}>
        <div className="w-full h-full absolute -z-10">
          <Aurora
            colorStops={["#ff0000", "#601515", "#FF3232"]}
            speed={1}
            amplitude={0.4}
          />
        </div>
        <Header />
        {children}
      </body>
    </html>
  );
}
